apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-ui-dev
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: angular-ui
      role: frontend
      env: dev
  template:
    metadata:
      name: frontend
      labels:
        app: angular-ui-frontend
        role: frontend
        env: dev
    spec:
      containers:
      - image: gcr.io/primeval-mark-254911/angular-ui:1.0.0
        name: angular-ui-app
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: "PORT"
          value: 80